name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - CI Job
    runs-on: ubuntu-latest  # Required by GitHub Actions, even if we're using a container
    container: node:20-alpine  # Use a lightweight Node container

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Yarn and Dependencies
        run: |
          # Enable Yarn using Corepack
          corepack enable
          corepack prepare yarn@stable --activate

          # Install project dependencies (use cache if available)
          yarn install --frozen-lockfile

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Run Nx Cloud Commands in Parallel
        run: |
          yarn nx-cloud record -- yarn nx format:check
          yarn nx affected --target=lint --parallel=3
          yarn nx affected --target=test --parallel=3 --ci --code-coverage
          yarn nx affected --target=build --parallel=3
